[target.xtensa-esp32-none-elf]
runner = "espflash flash -b no-reset --monitor --log-format defmt"


[env]
DEFMT_LOG = "trace"

[build]
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "link-arg=-nostartfiles",
  "-C", "link-arg=-Tdefmt.x",
]

target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["core"]
