[target.xtensa-esp32-none-elf]
runner = "espflash flash -b no-reset"


[env]
ESP_LOGLEVEL="trace"

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["core"]
